spring.application.name=message-to-future-api
spring.profiles.default=${APP_PROFILE:dev}

server.port=${SERVER_PORT:8090}

# locale config
spring.mvc.locale.resolve=fixed
spring.mvc.locale=pt_BR

security.jwt.secret=${JWT_SECRET:}
security.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:30m}
security.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:7d}

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-message-to-future-api.html
springdoc.api-docs.path=/docs-message-to-future-api
springdoc.packagesToScan=com.jacob_araujo.message_to_future_api.web.controller
